stages:
  - linting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --import-order-style=pycharm --exclude=migrations

black_check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .

test:
  stage: testing
  image: registry.gitlab.com/pipeline-components/python:latest
  script:
    - pip install -r requirements/dev.txt
    - cd lyceum
    - python3 manage.py test .